In [8]:
import math as m

In [11]:
print(m.sqrt(9))
math.sqrt(16)

3.0


4.0

In [12]:
from math import *

In [25]:
sqrt(9)

3.0

In [19]:
ceil(34.34)

35

In [24]:
round(45.5)

46

In [20]:
floor(67.1)

67

In [21]:
floor(67.8)

67

In [22]:
5/2

2.5

In [23]:
5//2

2

In [26]:
[1,2,3,4,5]

[1, 2, 3, 4, 5]

In [27]:
ma = [[12,23],[56,78],[89,90]]

In [28]:
ma

[[12, 23], [56, 78], [89, 90]]

In [29]:
import numpy as np

In [30]:
num_array = np.arange(10)
num_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
type(num_array)

numpy.ndarray

In [33]:
type('5')

str

In [34]:
num_array[0]

0

In [35]:
num_array[1]

1

In [46]:
a = [23,45,67,6]
b = [78,90,78]
result = []
for i,j in zip(a,b):
    result.append(i+j)

In [47]:
result

[101, 135, 145]

In [48]:
#. List Compare to Array
import time
li1 = range(100000)
li2 = range(100000)
a1 = np.arange(100000)
a2 = np.arange(100000)
output = []
start = time.time()
for i,j in zip(li1,li2):
    output.append(i+j)
end = time.time()
print("Python List took: ",(end-start)*1000)
start1 = time.time()
output = a1 + a2
end1 = time.time()
print("Array took: ",(end1-start1)*1000)

Python List took:  35.85100173950195
Array took:  3.226041793823242


In [51]:
a = np.array([34,56,78,45])
b = np.array([4,6,8,9])

In [52]:
a + b

array([38, 62, 86, 54])

In [53]:
a - b

array([30, 50, 70, 36])

In [54]:
a*b

array([136, 336, 624, 405])

In [55]:
a/b

array([8.5       , 9.33333333, 9.75      , 5.        ])

In [56]:
a.ndim

1

In [57]:
mat = np.array([[34,45],[56,78],[3,4]])
mat

array([[34, 45],
       [56, 78],
       [ 3,  4]])

In [58]:
mat.ndim

2

In [59]:
mat.shape

(3, 2)

In [60]:
mat.dtype

dtype('int64')

In [63]:
np.array([45,89,78])

array([45, 89, 78])

In [66]:
np.zeros((3,3),dtype = 'int64')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [65]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [67]:
mat

array([[34, 45],
       [56, 78],
       [ 3,  4]])

In [70]:
mat.reshape(6,1)

array([[34],
       [45],
       [56],
       [78],
       [ 3],
       [ 4]])

In [73]:
mat.reshape(-1,6)

array([[34, 45, 56, 78,  3,  4]])

In [75]:
mat.reshape(3,-1)

array([[34, 45],
       [56, 78],
       [ 3,  4]])

In [76]:
mat.reshape(-1,3)

array([[34, 45, 56],
       [78,  3,  4]])

In [78]:
mat2 = mat.ravel()

In [79]:
mat2.shape

(6,)

In [82]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [83]:
mat

array([[34, 45],
       [56, 78],
       [ 3,  4]])

In [84]:
mat.max()

78

In [85]:
mat.min()

3

In [86]:
mat.sum()

220

In [87]:
mat.sum(axis = 0) # 0 = Column and 1 = row numpyarray

array([ 93, 127])

In [88]:
mat.sum(axis = 1)

array([ 79, 134,   7])

In [89]:
mat.min(axis = 1)

array([34, 56,  3])

In [91]:
mat.max(axis = 0)

array([56, 78])

In [92]:
np.sqrt(mat)

array([[5.83095189, 6.70820393],
       [7.48331477, 8.83176087],
       [1.73205081, 2.        ]])

In [98]:
np.random.randint(1,50,5)

array([11,  5, 26,  7, 27])

In [103]:
np.random.rand(10)

array([0.28024841, 0.55371596, 0.08971537, 0.44482508, 0.51977288,
       0.26648072, 0.58454304, 0.58144722, 0.27543597, 0.68761843])

In [104]:
np.random.randn(10)

array([-0.67483679,  0.18058235,  0.06545527,  0.08330528,  1.63056663,
       -0.00556814,  0.67646889, -1.79780123, -2.13018794,  0.97100412])