In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier as knc

In [5]:
iris_data = load_iris()

In [6]:
iris_data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [7]:
iris_data['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
iris_data['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [9]:
iris_data['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
iris_data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [11]:
df = pd.DataFrame()

In [12]:
sl = iris_data['data'][:,0]
sw = iris_data['data'][:,1]
pl = iris_data['data'][:,2]
pw = iris_data['data'][:,3]
target = iris_data['target']

In [13]:
df['sepal_length'] = sl
df['sepal_width'] = sw
df['petal_length'] = pl
df['petal_width'] = pw
df['target'] = target

In [14]:
df.head()

sepal_length  sepal_width  petal_length  petal_width  target
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0

In [15]:
df.to_csv('iris_data.csv')

## 1. Calculate distance
## 2. Get NN
## 3. Make Prediction

In [16]:
# First method
data = np.array(df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'target']])

In [17]:
data_len = np.random.permutation(len(data))

In [18]:
data = data[data_len]

In [19]:
#x = np.array([23,56,78,90])
#le = np.random.permutation(len(x))

In [20]:
# Second method
newdata = iris_data['data']
newdata = np.insert(newdata,4,target,axis=1)

In [21]:
learning_data = newdata[data_len]

In [22]:
learning_data

array([[4.8, 3. , 1.4, 0.1, 0. ],
       [6. , 2.2, 4. , 1. , 1. ],
       [6.1, 3. , 4.6, 1.4, 1. ],
       [5. , 3.5, 1.6, 0.6, 0. ],
       [5.5, 2.4, 3.8, 1.1, 1. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.6, 2.7, 4.2, 1.3, 1. ],
       [5.8, 2.7, 4.1, 1. , 1. ],
       [5.1, 2.5, 3. , 1.1, 1. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [6.9, 3.1, 5.1, 2.3, 2. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [7.4, 2.8, 6.1, 1.9, 2. ],
       [6.5, 3.2, 5.1, 2. , 2. ],
       [7.7, 2.8, 6.7, 2. , 2. ],
       [7.6, 3. , 6.6, 2.1, 2. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5.6, 2.9, 3.6, 1.3, 1. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [5.5, 3.5, 1.3, 0.2, 0. ],
       [6.6, 3. , 4.4, 1.4, 1. ],
       [5.7, 2.9, 4.2, 1.3, 1. ],
       [6.3, 3.3, 6. , 2.5, 2. ],
       [5.8, 2.7, 5.1, 1.9, 2. ],
       [6.3, 2.7, 4.9, 1.8, 2. ],
       [6. , 2.2, 5. , 1.5, 2. ],
       [7.1, 3

## Find Euclidean Distance sqrt((x1-x2)^2+(y1-y2)^2+(z1-z2)^2+(w1-w2)^2)

In [23]:
def Find_Euclidean_Distance(point1,point2):
    distance = 0
    if (len(point1)==len(point2)):
        for i in range(len(point1)-1):
            distance += (point1[i] - point2[i])**2
            
            
    return distance  ** 0.5



In [24]:
Find_distance(learning_data[0], learning_data[1])

NameError: name 'Find_distance' is not defined

In [25]:
Find_Euclidean_Distance(learning_data[0], learning_data[1])

3.1064449134018135

## Get NN

In [26]:
def Find_distance(point, newpoint):
    if (len(point) == len(newpoint)):
        return np.sqrt(sum((point - newpoint)[:-1]**2))
    
def Get_NN(Train,Test_row,K):
    """
    1. Find distance of testrow with all training data points
    2. sort our distance / ascend to descend
    3. slice data based on K value
    4. Finda max Classes
    5. Prediction
    """
    target_names = iris_data['target_names']
    Distance = []
    for row in Train:
        dis = Find_distance(row,Test_row)
        Distance.append(dis)
    Distance = np.array(Distance)    
    index_dist = Distance.argsort()
    Train = Train[index_dist]
    Distance = Distance[index_dist]
    nn = Train[:K]
    Classes = []
    for i in nn:
        Classes.append(i[-1])
    pred = max(Classes)
    return np.array(pred, dtype = 'int'), target_names[int(pred)]

def Accuracy(y_actual,y_pred):
    if(len(y_actual) == len(y_pred)):
        v = 0
        for i,j in zip(y_actual,y_pred):
            if (i == j):
                v+=1
        acc = v/len(y_actual)*100
        return acc

In [27]:
ypredicted = Get_NN(learning_data, [3.8, 1.8 , 1.5, 1.4, 2. ], 5)

In [28]:
ypredicted

(array(0), 'setosa')

In [29]:
model = knc(n_neighbors = 5)
mt = model.fit(iris_data['data'], iris_data['target'])

In [30]:
ypred = mt.predict(iris_data['data'])

In [31]:
ypred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [32]:
Accuracy(iris_data['target'],ypred)

96.66666666666667

In [33]:
from sklearn.metrics import accuracy_score

In [34]:
accuracy_score(iris_data['target'],ypred) * 100

96.66666666666667

In [ ]:
#Logistic regression // only works for two classes
#KNN
#Decision Tree
#Random Forest
#SVM
#Naive Bayes